# 文件命名校验规则. https://ls-lint.org
#
# kebab-case | camelCase | PascalCase
# regex:[a-z|.|-]+

ls:
  .js: kebab-case | kebabcase | pointcase
  .ts: kebab-case | kebabcase | pointcase
  .enum.ts: kebab-case | kebabcase | pointcase
  .hooks.ts: kebab-case | kebabcase | pointcase
  .config.ts: kebab-case | kebabcase | pointcase
  .store.ts: kebab-case | kebabcase | pointcase
  .type.ts: kebab-case | kebabcase | pointcase
  .d.ts: kebab-case | kebabcase | pointcase
  .tsx: kebab-case | kebabcase | pointcase
  .css: kebab-case | kebabcase | pointcase
  .scss: kebab-case | kebabcase | pointcase
  .mixin.scss: kebab-case | kebabcase | pointcase
  .json: kebab-case | kebabcase | pointcase

ignore:
  - dist
  - test
  - docs
  - node_modules
  - .git
  - .cz-config.js
  - .release-it.js
  - _webview
