# 文件命名校验规则. https://ls-lint.org
#
# kebab-case | camelCase | PascalCase
# regex:[a-z|.|-]+

ls:
  .js: kebabcase | pointcase
  .ts: kebabcase | pointcase
  .enum.ts: kebabcase | pointcase
  .hooks.ts: kebabcase | pointcase
  .config.ts: kebabcase | pointcase
  .store.ts: kebabcase | pointcase
  .d.ts: kebabcase | pointcase
  .tsx: kebabcase | pointcase
  .css: kebabcase | pointcase
  .scss: kebabcase | pointcase
  .mixin.scss: kebabcase | pointcase
  .json: kebabcase | pointcase

ignore:
  - dist
  - test
  - docs
  - node_modules
  - .git
  - .cz-config.js
  - _webview
